### ISSUE TITLE
Wrong definition of pyenv-interactive-completion-function.

### ISSUE THREAD

**Issue by skrech** [aiguofer/pyenv.el#2]
Hello,
I'm switching from pyenv-mode to pyenv.el because the first one is not supported anymore.

I installed pyenv.el with straight (I installed straight.el only for this package... it will be great to have such a small project as a ordinary package in package.el) and trying "M-x pyenv-use" was giving me invalid-function error. I checked the code and saw this defcustom:
```
(defcustom pyenv-interactive-completion-function 
  "The function which is used by pyenv.el to interactivly complete user input."
  (if ido-mode 'ido-completing-read 'completing-read)
  :group 'pyenv
  :type 'function)
```

Should be changed to:
```

(defcustom pyenv-interactive-completion-function (if ido-mode 'ido-completing-read 'completing-read)
  "The function which is used by pyenv.el to interactivly complete user input."
  :group 'pyenv
  :type 'function)
```

**Comment by aiguofer** [comment]
Hey, thanks for pointing that out! Fixed in 8b12ff422ca108700889db317c81b6f58cad795f
